name: example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  asset_manager_tool:
    path: ../

flutter:
  assets:
    - assets/options/
    - assets/img/

  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont-Italic.ttf
        - asset: assets/fonts/iconfont-Regular.ttf
          style: italic

asset_manager_tool:
  dustbin-path: assets/.asset_dustbin/
  list-path: assets/asset_list.dart
