name: asset_manager_tool
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/tengfei5000nian/asset_manager_tool

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.1
  watcher: ^1.0.1
  logging: ^1.1.0
  yaml: ^3.1.1
  path: ^1.8.2
  crypto: ^3.0.2
  image: ^3.2.0
  glob: ^2.1.0
  io: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
